# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensorgrpc.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sensorgrpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10sensorgrpc.proto\x12\nsensorgrpc\";\n\x0b\x44\x61taRequest\x12\x10\n\x08\x66unction\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\"\x0b\n\tDataReply\"\x0e\n\x0cHeartRequest\"\x0c\n\nHeartReply\"0\n\x0eMinioFileChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"&\n\x13MinioUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xcc\x01\n\x05Oskit\x12:\n\x08PushData\x12\x17.sensorgrpc.DataRequest\x1a\x15.sensorgrpc.DataReply\x12>\n\nCheckHeart\x12\x18.sensorgrpc.HeartRequest\x1a\x16.sensorgrpc.HeartReply\x12G\n\x06Upload\x12\x1a.sensorgrpc.MinioFileChunk\x1a\x1f.sensorgrpc.MinioUploadResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensorgrpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=32
  _globals['_DATAREQUEST']._serialized_end=91
  _globals['_DATAREPLY']._serialized_start=93
  _globals['_DATAREPLY']._serialized_end=104
  _globals['_HEARTREQUEST']._serialized_start=106
  _globals['_HEARTREQUEST']._serialized_end=120
  _globals['_HEARTREPLY']._serialized_start=122
  _globals['_HEARTREPLY']._serialized_end=134
  _globals['_MINIOFILECHUNK']._serialized_start=136
  _globals['_MINIOFILECHUNK']._serialized_end=184
  _globals['_MINIOUPLOADRESPONSE']._serialized_start=186
  _globals['_MINIOUPLOADRESPONSE']._serialized_end=224
  _globals['_OSKIT']._serialized_start=227
  _globals['_OSKIT']._serialized_end=431
# @@protoc_insertion_point(module_scope)
