# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from backend.grpc import sensorgrpc_pb2 as sensorgrpc__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sensorgrpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OskitStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushData = channel.unary_unary(
                '/sensorgrpc.Oskit/PushData',
                request_serializer=sensorgrpc__pb2.DataRequest.SerializeToString,
                response_deserializer=sensorgrpc__pb2.DataReply.FromString,
                _registered_method=True)
        self.CheckHeart = channel.unary_unary(
                '/sensorgrpc.Oskit/CheckHeart',
                request_serializer=sensorgrpc__pb2.HeartRequest.SerializeToString,
                response_deserializer=sensorgrpc__pb2.HeartReply.FromString,
                _registered_method=True)
        self.Upload = channel.stream_unary(
                '/sensorgrpc.Oskit/Upload',
                request_serializer=sensorgrpc__pb2.MinioFileChunk.SerializeToString,
                response_deserializer=sensorgrpc__pb2.MinioUploadResponse.FromString,
                _registered_method=True)


class OskitServicer:
    """Missing associated documentation comment in .proto file."""

    def PushData(self, request, context):
        """Push agent datas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHeart(self, request, context):
        """Detect server heart
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upload(self, request_iterator, context):
        """Client file saved to storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OskitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushData': grpc.unary_unary_rpc_method_handler(
                    servicer.PushData,
                    request_deserializer=sensorgrpc__pb2.DataRequest.FromString,
                    response_serializer=sensorgrpc__pb2.DataReply.SerializeToString,
            ),
            'CheckHeart': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHeart,
                    request_deserializer=sensorgrpc__pb2.HeartRequest.FromString,
                    response_serializer=sensorgrpc__pb2.HeartReply.SerializeToString,
            ),
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=sensorgrpc__pb2.MinioFileChunk.FromString,
                    response_serializer=sensorgrpc__pb2.MinioUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensorgrpc.Oskit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sensorgrpc.Oskit', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Oskit:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensorgrpc.Oskit/PushData',
            sensorgrpc__pb2.DataRequest.SerializeToString,
            sensorgrpc__pb2.DataReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHeart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensorgrpc.Oskit/CheckHeart',
            sensorgrpc__pb2.HeartRequest.SerializeToString,
            sensorgrpc__pb2.HeartReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/sensorgrpc.Oskit/Upload',
            sensorgrpc__pb2.MinioFileChunk.SerializeToString,
            sensorgrpc__pb2.MinioUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
