# Generated by Django 4.2.3 on 2026-05-04 09:24

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='users',
            name='enable',
            field=models.IntegerField(default=1, verbose_name='是否启用 1=正常 2=冻结'),
        ),
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(default='系统用户', max_length=50, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='users',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='用户UUID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=50, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
