# Generated by Django 4.2.3 on 2026-05-05 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_add_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.users', verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email', 'code', 'used'], name='idx_email_code_used'),
        ),
    ]
