# Generated by Django 4.2.3 on 2026-05-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_update_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_id', models.PositiveIntegerField(unique=True, verbose_name='角色ID')),
                ('authority_name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('default_router', models.CharField(default='dashboard', max_length=255, verbose_name='默认路由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_scope', to='backend.authority', verbose_name='数据权限范围')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='backend.authority', verbose_name='父角色')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'sys_authorities',
                'ordering': ['authority_id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='路由路径')),
                ('name', models.CharField(max_length=100, verbose_name='路由名称')),
                ('component', models.CharField(blank=True, max_length=255, verbose_name='前端组件路径')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('meta', models.JSONField(default=dict, verbose_name='菜单元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'sys_base_menus',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='MenuButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='按钮标识')),
                ('desc', models.CharField(blank=True, max_length=255, verbose_name='按钮描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='backend.menu', verbose_name='所属菜单')),
            ],
            options={
                'verbose_name': '菜单按钮',
                'verbose_name_plural': '菜单按钮',
                'db_table': 'sys_base_menu_btns',
            },
        ),
        migrations.CreateModel(
            name='UserAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.authority', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色关联',
                'verbose_name_plural': '用户角色关联',
                'db_table': 'sys_user_authority',
                'unique_together': {('user', 'authority')},
            },
        ),
        migrations.CreateModel(
            name='AuthorityMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.authority', verbose_name='角色')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.menu', verbose_name='菜单')),
            ],
            options={
                'verbose_name': '角色菜单关联',
                'verbose_name_plural': '角色菜单关联',
                'db_table': 'sys_authority_menus',
                'unique_together': {('authority', 'menu')},
            },
        ),
        migrations.CreateModel(
            name='AuthorityButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.authority', verbose_name='角色')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.menubutton', verbose_name='按钮')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.menu', verbose_name='菜单')),
            ],
            options={
                'verbose_name': '角色按钮权限',
                'verbose_name_plural': '角色按钮权限',
                'db_table': 'sys_authority_btns',
                'unique_together': {('authority', 'menu', 'button')},
            },
        ),
    ]
