# Generated by Django 4.2.3 on 2026-05-07 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_fix_menu_children_related_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['id'], 'verbose_name': '集群', 'verbose_name_plural': '集群'},
        ),
        migrations.AddField(
            model_name='cluster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='vcenter_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='vCenter ID'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='集群名称'),
        ),
        migrations.AlterModelTable(
            name='cluster',
            table='clusters',
        ),
    ]
