# Generated by Django 4.2.3 on 2026-05-07 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_cluster_options_cluster_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='管理IP')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='密码（加密存储）')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], default='offline', max_length=20)),
                ('os_type', models.CharField(blank=True, max_length=50, verbose_name='操作系统')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.cluster', verbose_name='所属集群')),
            ],
            options={
                'verbose_name': '宿主机',
                'verbose_name_plural': '宿主机',
                'db_table': 'hosts',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Hosts',
        ),
    ]
