# Generated by Django 4.2.3 on 2026-05-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_add_host_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='VM名称')),
                ('uuid', models.CharField(max_length=100, unique=True, verbose_name='UUID')),
                ('status', models.CharField(choices=[('stopped', '已停止'), ('running', '运行中'), ('paused', '暂停'), ('suspended', '挂起')], default='stopped', max_length=20, verbose_name='状态')),
                ('vcpu', models.IntegerField(default=1, verbose_name='虚拟CPU核数')),
                ('memory', models.BigIntegerField(default=0, verbose_name='内存(字节)')),
                ('disk', models.BigIntegerField(default=0, verbose_name='磁盘(字节)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC地址')),
                ('os_type', models.CharField(blank=True, max_length=50, verbose_name='操作系统')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.cluster', verbose_name='所属集群')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='backend.host', verbose_name='所属宿主机')),
            ],
            options={
                'verbose_name': '虚拟机',
                'verbose_name_plural': '虚拟机',
                'db_table': 'vms',
                'ordering': ['id'],
            },
        ),
    ]
