# Generated by Django 4.2.3 on 2026-05-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_add_vm_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOFileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True, verbose_name='文件名')),
                ('size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('md5sum', models.CharField(max_length=32, verbose_name='MD5校验')),
                ('status', models.CharField(choices=[('available', '可用'), ('uploading', '上传中'), ('error', '错误'), ('disabled', '禁用')], default='available', max_length=20, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ISO文件状态',
                'verbose_name_plural': 'ISO文件状态',
                'db_table': 'iso_file_status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('job_type', models.CharField(choices=[('os_install', '系统安装'), ('os_migrate', '系统迁移'), ('hardware_collect', '硬件信息采集')], max_length=50, verbose_name='任务类型')),
                ('target', models.CharField(max_length=255, verbose_name='目标')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='结果详情')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '任务状态',
                'verbose_name_plural': '任务状态',
                'db_table': 'job_status',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutIpSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True, verbose_name='MAC地址')),
                ('sn', models.CharField(max_length=100, verbose_name='序列号')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '出口IP序列号',
                'verbose_name_plural': '出口IP序列号',
                'db_table': 'out_ip_sn',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PXEServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField(unique=True, verbose_name='服务器IP')),
                ('interface', models.CharField(default='eth0', max_length=100, verbose_name='网卡')),
                ('dhcp_range_start', models.GenericIPAddressField(verbose_name='DHCP起始IP')),
                ('dhcp_range_end', models.GenericIPAddressField(verbose_name='DHCP结束IP')),
                ('subnet', models.CharField(max_length=255, verbose_name='子网')),
                ('gateway', models.GenericIPAddressField(verbose_name='网关')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('error', '错误')], default='active', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PXE服务器状态',
                'verbose_name_plural': 'PXE服务器状态',
                'db_table': 'pxe_server_status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RepoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='仓库名称')),
                ('repo_type', models.CharField(choices=[('yum', 'YUM'), ('iso', 'ISO'), ('http', 'HTTP')], max_length=20, verbose_name='仓库类型')),
                ('base_url', models.URLField(verbose_name='仓库地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '仓库状态',
                'verbose_name_plural': '仓库状态',
                'db_table': 'repo_status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True, verbose_name='MAC地址')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MAC地址白名单',
                'verbose_name_plural': 'MAC地址白名单',
                'db_table': 'white_list',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KickStartFileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('kernel_options', models.JSONField(blank=True, default=dict, verbose_name='内核参数')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.repostatus', verbose_name='关联仓库')),
            ],
            options={
                'verbose_name': 'Kickstart文件状态',
                'verbose_name_plural': 'Kickstart文件状态',
                'db_table': 'kickstart_file_status',
                'ordering': ['id'],
            },
        ),
    ]
