# Generated by Django 4.2.3 on 2026-05-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_add_osdeploy_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBalancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('vip_address', models.GenericIPAddressField(verbose_name='VIP地址')),
                ('port', models.IntegerField(default=80, verbose_name='端口')),
                ('algorithm', models.CharField(choices=[('round_robin', '轮询'), ('least_conn', '最少连接'), ('source', '源IP')], default='round_robin', max_length=20, verbose_name='负载算法')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '未激活'), ('error', '异常')], default='active', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '负载均衡器',
                'verbose_name_plural': '负载均衡器',
                'db_table': 'load_balancer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LBPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('http', 'HTTP'), ('https', 'HTTPS')], max_length=10, verbose_name='协议')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loadbalancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.loadbalancer', verbose_name='负载均衡器')),
            ],
            options={
                'verbose_name': '后端池',
                'verbose_name_plural': '后端池',
                'db_table': 'lb_pool',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LBHealthMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_type', models.CharField(choices=[('tcp', 'TCP'), ('http', 'HTTP'), ('ping', 'PING')], max_length=10, verbose_name='检查类型')),
                ('interval', models.IntegerField(default=5, verbose_name='检查间隔(秒)')),
                ('timeout', models.IntegerField(default=3, verbose_name='超时(秒)')),
                ('retry', models.IntegerField(default=3, verbose_name='重试次数')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.lbpool', verbose_name='后端池')),
            ],
            options={
                'verbose_name': '健康检查',
                'verbose_name_plural': '健康检查',
                'db_table': 'lb_health_monitor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LBMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='backend.lbpool', verbose_name='后端池')),
            ],
            options={
                'verbose_name': '池成员',
                'verbose_name_plural': '池成员',
                'db_table': 'lb_member',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LBListener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('http', 'HTTP'), ('https', 'HTTPS')], max_length=10, verbose_name='协议')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loadbalancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='backend.loadbalancer', verbose_name='负载均衡器')),
            ],
            options={
                'verbose_name': '监听器',
                'verbose_name_plural': '监听器',
                'db_table': 'lb_listener',
                'ordering': ['-created_at'],
            },
        ),
    ]