# Generated by Django 4.2.20 on 2026-05-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_add_network_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeguardDeploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部署名称')),
                ('target_hosts', models.JSONField(default=list, verbose_name='目标主机列表')),
                ('safeguard_type', models.CharField(default='safeguardx86', max_length=50, verbose_name='安全组件类型')),
                ('arch', models.CharField(choices=[('x86', 'X86'), ('arm', 'ARM')], default='x86', max_length=20, verbose_name='架构')),
                ('host', models.CharField(blank=True, max_length=100, verbose_name='目标主机IP')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='密码')),
                ('port', models.CharField(default='22', max_length=10, verbose_name='端口')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='结果详情')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Safeguard部署',
                'verbose_name_plural': 'Safeguard部署',
                'db_table': 'safeguard_deploy',
                'ordering': ['-created_at'],
            },
        ),
    ]
