# Generated by Django 4.2.20 on 2026-05-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_safeguarddeploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='arch_info',
            field=models.TextField(blank=True, verbose_name='内核架构信息'),
        ),
        migrations.AddField(
            model_name='host',
            name='asset_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='资产编号'),
        ),
        migrations.AddField(
            model_name='host',
            name='base_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='基地'),
        ),
        migrations.AddField(
            model_name='host',
            name='bios_config',
            field=models.TextField(blank=True, verbose_name='BIOS配置要求'),
        ),
        migrations.AddField(
            model_name='host',
            name='bond_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bond模式'),
        ),
        migrations.AddField(
            model_name='host',
            name='business_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='业务IP地址'),
        ),
        migrations.AddField(
            model_name='host',
            name='business_bond_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='业务Bond模式'),
        ),
        migrations.AddField(
            model_name='host',
            name='business_ifname',
            field=models.CharField(blank=True, max_length=50, verbose_name='业务接口名称'),
        ),
        migrations.AddField(
            model_name='host',
            name='business_netmask',
            field=models.CharField(blank=True, max_length=20, verbose_name='业务网络掩码'),
        ),
        migrations.AddField(
            model_name='host',
            name='business_nic1',
            field=models.CharField(blank=True, max_length=50, verbose_name='业务网卡1'),
        ),
        migrations.AddField(
            model_name='host',
            name='business_nic2',
            field=models.CharField(blank=True, max_length=50, verbose_name='业务网卡2'),
        ),
        migrations.AddField(
            model_name='host',
            name='business_vlan',
            field=models.CharField(blank=True, max_length=20, verbose_name='业务VLAN'),
        ),
        migrations.AddField(
            model_name='host',
            name='cabinet_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='机柜编号'),
        ),
        migrations.AddField(
            model_name='host',
            name='cell_vip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Cell VIP'),
        ),
        migrations.AddField(
            model_name='host',
            name='cluster_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='集群名称'),
        ),
        migrations.AddField(
            model_name='host',
            name='cpu_info',
            field=models.TextField(blank=True, verbose_name='CPU信息'),
        ),
        migrations.AddField(
            model_name='host',
            name='disk_info',
            field=models.TextField(blank=True, verbose_name='磁盘信息'),
        ),
        migrations.AddField(
            model_name='host',
            name='dmesg_info',
            field=models.TextField(blank=True, verbose_name='dmesg信息'),
        ),
        migrations.AddField(
            model_name='host',
            name='flag',
            field=models.BooleanField(default=True, verbose_name='标记'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_type',
            field=models.CharField(default='VMHost', max_length=50, verbose_name='设备分类'),
        ),
        migrations.AddField(
            model_name='host',
            name='ipmi_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IPMI地址'),
        ),
        migrations.AddField(
            model_name='host',
            name='ipmi_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='IPMI密码'),
        ),
        migrations.AddField(
            model_name='host',
            name='ipmi_user',
            field=models.CharField(blank=True, max_length=50, verbose_name='IPMI用户名'),
        ),
        migrations.AddField(
            model_name='host',
            name='ipmi_vlan',
            field=models.CharField(blank=True, max_length=20, verbose_name='IPMI VLAN'),
        ),
        migrations.AddField(
            model_name='host',
            name='is_bind_cell_type',
            field=models.BooleanField(default=False, verbose_name='是否绑定cell'),
        ),
        migrations.AddField(
            model_name='host',
            name='is_cluster_type',
            field=models.BooleanField(default=False, verbose_name='是否有集群属性'),
        ),
        migrations.AddField(
            model_name='host',
            name='is_warranty_period',
            field=models.BooleanField(default=False, verbose_name='是否在保修期'),
        ),
        migrations.AddField(
            model_name='host',
            name='is_zone_type',
            field=models.BooleanField(default=False, verbose_name='是否有专区属性'),
        ),
        migrations.AddField(
            model_name='host',
            name='lldp_infos',
            field=models.JSONField(default=list, verbose_name='LLDP信息'),
        ),
        migrations.AddField(
            model_name='host',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, verbose_name='MAC地址'),
        ),
        migrations.AddField(
            model_name='host',
            name='manage_address_ipv6',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IPv6地址'),
        ),
        migrations.AddField(
            model_name='host',
            name='manage_netmask_ipv6',
            field=models.CharField(blank=True, max_length=20, verbose_name='管理IPv6掩码'),
        ),
        migrations.AddField(
            model_name='host',
            name='manage_nic1',
            field=models.CharField(blank=True, max_length=50, verbose_name='管理网卡1'),
        ),
        migrations.AddField(
            model_name='host',
            name='manage_nic2',
            field=models.CharField(blank=True, max_length=50, verbose_name='管理网卡2'),
        ),
        migrations.AddField(
            model_name='host',
            name='manage_vlan',
            field=models.CharField(blank=True, max_length=20, verbose_name='管理VLAN'),
        ),
        migrations.AddField(
            model_name='host',
            name='memory_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='内存信息'),
        ),
        migrations.AddField(
            model_name='host',
            name='mount_info',
            field=models.TextField(blank=True, verbose_name='mount信息'),
        ),
        migrations.AddField(
            model_name='host',
            name='netmask',
            field=models.CharField(blank=True, max_length=20, verbose_name='管理网络掩码'),
        ),
        migrations.AddField(
            model_name='host',
            name='network_info',
            field=models.TextField(blank=True, verbose_name='网络信息'),
        ),
        migrations.AddField(
            model_name='host',
            name='ntp_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='NTP地址'),
        ),
        migrations.AddField(
            model_name='host',
            name='os_version',
            field=models.TextField(blank=True, verbose_name='操作系统版本'),
        ),
        migrations.AddField(
            model_name='host',
            name='other_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='其他IP地址'),
        ),
        migrations.AddField(
            model_name='host',
            name='other_ifname',
            field=models.CharField(blank=True, max_length=50, verbose_name='其他接口名称'),
        ),
        migrations.AddField(
            model_name='host',
            name='other_netmask',
            field=models.CharField(blank=True, max_length=20, verbose_name='其他网络掩码'),
        ),
        migrations.AddField(
            model_name='host',
            name='other_nic1',
            field=models.CharField(blank=True, max_length=50, verbose_name='其他网卡1'),
        ),
        migrations.AddField(
            model_name='host',
            name='other_nic2',
            field=models.CharField(blank=True, max_length=50, verbose_name='其他网卡2'),
        ),
        migrations.AddField(
            model_name='host',
            name='other_vlan',
            field=models.CharField(blank=True, max_length=20, verbose_name='其他VLAN'),
        ),
        migrations.AddField(
            model_name='host',
            name='raid',
            field=models.CharField(blank=True, max_length=100, verbose_name='RAID配置'),
        ),
        migrations.AddField(
            model_name='host',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='host',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='序列号'),
        ),
        migrations.AddField(
            model_name='host',
            name='server_brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='服务器品牌'),
        ),
        migrations.AddField(
            model_name='host',
            name='server_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='服务器型号'),
        ),
        migrations.AddField(
            model_name='host',
            name='server_room_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='机房编号'),
        ),
        migrations.AddField(
            model_name='host',
            name='server_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='服务器大小'),
        ),
        migrations.AddField(
            model_name='host',
            name='storage_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='存储IP地址'),
        ),
        migrations.AddField(
            model_name='host',
            name='storage_ifname',
            field=models.CharField(blank=True, max_length=50, verbose_name='存储接口名称'),
        ),
        migrations.AddField(
            model_name='host',
            name='storage_netmask',
            field=models.CharField(blank=True, max_length=20, verbose_name='存储网络掩码'),
        ),
        migrations.AddField(
            model_name='host',
            name='storage_vlan',
            field=models.CharField(blank=True, max_length=20, verbose_name='存储VLAN'),
        ),
        migrations.AddField(
            model_name='host',
            name='uptime',
            field=models.CharField(blank=True, max_length=100, verbose_name='运行时间'),
        ),
        migrations.AddField(
            model_name='host',
            name='use_for',
            field=models.CharField(blank=True, max_length=100, verbose_name='用途'),
        ),
        migrations.AddField(
            model_name='host',
            name='use_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='使用人'),
        ),
        migrations.AddField(
            model_name='vm',
            name='management_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP'),
        ),
        migrations.AddField(
            model_name='vm',
            name='storage_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='存储IP'),
        ),
        migrations.AddField(
            model_name='vm',
            name='vm_disk_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='虚拟机磁盘路径'),
        ),
        migrations.AddField(
            model_name='vm',
            name='vm_image_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='虚拟机镜像路径'),
        ),
        migrations.AddField(
            model_name='vm',
            name='vm_network_bridge',
            field=models.CharField(blank=True, max_length=50, verbose_name='虚拟机网桥'),
        ),
    ]
