# Generated by Django 4.2.20 on 2026-05-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_host_model_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='datadisk',
            field=models.JSONField(blank=True, default=list, verbose_name='数据盘信息'),
        ),
        migrations.AddField(
            model_name='vm',
            name='imageid',
            field=models.CharField(blank=True, max_length=100, verbose_name='镜像ID'),
        ),
        migrations.AddField(
            model_name='vm',
            name='status_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='状态消息'),
        ),
        migrations.AddField(
            model_name='vm',
            name='sysdisk',
            field=models.JSONField(blank=True, default=dict, verbose_name='系统盘信息'),
        ),
    ]
