# Generated by Django 4.2.20 on 2026-05-28 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_extend_vm_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='镜像ID')),
                ('name', models.CharField(max_length=255, verbose_name='镜像名称')),
                ('ostype', models.CharField(blank=True, max_length=50, verbose_name='操作系统类型')),
                ('path', models.CharField(max_length=255, verbose_name='镜像路径')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.host', verbose_name='所属宿主机')),
            ],
            options={
                'verbose_name': '虚拟机镜像',
                'verbose_name_plural': '虚拟机镜像',
                'db_table': 'images',
                'ordering': ['id'],
            },
        ),
    ]
