# Generated by Django 4.2.20 on 2026-05-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_add_image_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('job_type', models.CharField(choices=[('os_install', '系统安装'), ('os_migrate', '系统迁移'), ('safeguard_deploy', '安全部署'), ('safeguard_rollback', '安全回滚'), ('hardware_collect', '硬件信息采集'), ('repo_sync', '仓库同步')], max_length=50, verbose_name='任务类型')),
                ('target', models.CharField(max_length=255, verbose_name='目标')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='结果详情')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'task',
                'ordering': ['-created_at'],
            },
        ),
    ]
