# Generated by Django 4.2.20 on 2026-06-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='repostatus',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=20, verbose_name='状态'),
        ),
    ]
