# Generated by Django 4.2.20 on 2026-06-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_add_repo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('job_type', models.CharField(choices=[('init', '初始化'), ('migrate', '迁移执行'), ('migrate_back', '迁移回滚'), ('post', '后置处理')], max_length=50, verbose_name='任务阶段')),
                ('migrate_type', models.CharField(blank=True, choices=[('iaas', 'IaaS'), ('yunguan', '云管')], max_length=20, verbose_name='迁移类型')),
                ('target_host', models.CharField(max_length=255, verbose_name='目标主机')),
                ('hosts_json', models.JSONField(blank=True, default=list, verbose_name='多主机列表')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('rebooting', '重启中')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='结果详情')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '迁移任务',
                'verbose_name_plural': '迁移任务',
                'db_table': 'migrate_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
