# Generated by Django 4.2.20 on 2026-06-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_migratejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeguarddeploy',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]
