# Generated by Django 4.2.20 on 2026-06-03 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_safeguarddeploy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.users', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='host',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.users', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.users', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='vm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.users', verbose_name='创建者'),
        ),
    ]
