# Generated by Django 4.2.20 on 2026-06-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_cluster_created_by_host_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='头像URL'),
        ),
        migrations.AddField(
            model_name='users',
            name='theme',
            field=models.CharField(blank=True, default='light', max_length=20, verbose_name='主题偏好'),
        ),
    ]
