# Generated by Django 4.2.20 on 2026-06-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_users_avatar_users_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
