# Generated by Django 4.2.20 on 2026-06-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_users_password_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='客户端IP')),
                ('function', models.CharField(max_length=255, verbose_name='功能标识')),
                ('data', models.TextField(verbose_name='上报数据')),
                ('time', models.CharField(max_length=50, verbose_name='上报时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
            ],
            options={
                'verbose_name': 'Sensor数据',
                'verbose_name_plural': 'Sensor数据',
                'db_table': 'sensor',
            },
        ),
    ]
