# Generated by Django 4.2.20 on 2026-06-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_add_sensor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='页面描述'),
        ),
    ]
