"""Kickstart 生成服务"""
import re
import logging
from typing import Optional, List
from backend.models.osdeploy import KickStartFileStatus, RepoStatus
from backend.models.host import Host

logger = logging.getLogger(__name__)


class KickstartService:
    """Kickstart 模板渲染与生成服务"""

    # 预置模板内容
    TEMPLATES = {
        "ks-standard.cfg": """# Kickstart configuration for standard CuLinux installation
# Generated by safeguard-web

# System authorization
auth --enableshadow --passalgo=sha512

# Installation method
url --url="{{repo_url}}"

# Language and keyboard
lang en_US.UTF-8
keyboard us

# Network configuration
network --bootproto=static --ip={{ip_address}} --netmask={{netmask}} --gateway={{gateway}} --nameserver={{nameserver}} --device={{nic}} --hostname={{hostname}} --onboot=yes

# Root password (hashed)
rootpw --iscrypted {{root_password_hash}}

# Security
timezone {{timezone}} --isUtc
firewall --disabled
selinux --disabled

# Partitioning
clearpart --all --initlabel
part /boot --fstype=xfs --size=1024
part / --fstype=xfs --size=1 --grow
part swap --size={{swap_size}}

# Bootloader
bootloader --location=mbr --driveorder=sda

# Installation mode
install
reboot

# Package selection
%packages
@base
@core
@development
%end

# Post-installation script
%post
# Configure network
systemctl enable network
%end
""",
        "ks-centos7.cfg": """# Kickstart configuration for CentOS 7
# Generated by safeguard-web

# Install from URL
url --url="{{repo_url}}"

# Language and keyboard
lang en_US.UTF-8
keyboard us

# Network
network --bootproto=static --ip={{ip_address}} --netmask={{netmask}} --gateway={{gateway}} --nameserver={{nameserver}} --device={{nic}} --hostname={{hostname}} --onboot=yes --ipv6=auto

# Root password
rootpw --iscrypted {{root_password_hash}}

# Timezone
timezone {{timezone}} --isUtc

# Security
firewall --disabled
selinux --disabled

# Partitioning
clearpart --all --initlabel
part /boot --fstype=xfs --size=1024
part / --fstype=xfs --size=1 --grow
part swap --size={{swap_size}}

# Bootloader
bootloader --location=mbr --driveorder=sda

auth --enableshadow --passalgo=sha512

# Install mode
install
reboot

%packages
@^minimal
@core
@development
%end

%post
systemctl enable sshd
%end
""",
        "ks-openeuler.cfg": """# Kickstart configuration for openEuler
# Generated by safeguard-web

# Install from URL
url --url="{{repo_url}}"

# Language
lang en_US.UTF-8
keyboard us

# Network
network --bootproto=static --ip={{ip_address}} --netmask={{netmask}} --gateway={{gateway}} --nameserver={{nameserver}} --device={{nic}} --hostname={{hostname}} --onboot=yes

# Root password
rootpw --iscrypted {{root_password_hash}}

# Timezone
timezone {{timezone}} --isUtc

# Security
firewall --disabled
selinux --disabled

# Partitioning
clearpart --all --initlabel
part /boot --fstype=ext4 --size=1024
part / --fstype=ext4 --size=1 --grow
part swap --size={{swap_size}}

# Bootloader
bootloader --location=mbr --driveorder=sda

auth --enableshadow --passalgo=sha512

# Install mode
install
reboot

%packages
@minimal-environment
%end

%post
systemctl enable sshd
%end
""",
    }

    @staticmethod
    def generate_kickstart(template_id: int, variables: dict) -> str:
        """基于模板生成 Kickstart 文件内容

        Args:
            template_id: Kickstart模板ID
            variables: 变量字典，如 {"hostname": "node1", "ip_address": "192.168.1.10"}

        Returns:
            渲染后的 Kickstart 内容
        """
        try:
            template = KickStartFileStatus.objects.get(pk=template_id)
            content = template.content
        except KickStartFileStatus.DoesNotExist:
            raise ValueError(f"Kickstart模板不存在: {template_id}")

        return KickstartService.render_template(content, variables)

    @staticmethod
    def render_template(content: str, variables: dict) -> str:
        """渲染模板内容，支持 {{variable}} 变量替换"""
        result = content
        for key, value in variables.items():
            placeholder = f"{{{{{key}}}}}"
            result = result.replace(placeholder, str(value) if value is not None else "")
        return result

    @staticmethod
    def auto_generate_kickstart(host_id: int, repo_id: int, os_type: str = "culinux") -> str:
        """根据主机信息自动全量生成 Kickstart 文件

        Args:
            host_id: 主机ID
            repo_id: 仓库ID
            os_type: 操作系统类型 (culinux/centos7/openeuler)

        Returns:
            完整的 Kickstart 内容
        """
        try:
            host = Host.objects.get(pk=host_id)
        except Host.DoesNotExist:
            raise ValueError(f"主机不存在: {host_id}")

        try:
            repo = RepoStatus.objects.get(pk=repo_id)
        except RepoStatus.DoesNotExist:
            raise ValueError(f"仓库不存在: {repo_id}")

        # 选择模板
        template_name = f"ks-{os_type}.cfg"
        if template_name not in KickstartService.TEMPLATES:
            template_name = "ks-standard.cfg"
        template_content = KickstartService.TEMPLATES[template_name]

        # 构建变量
        variables = KickstartService._build_host_variables(host, repo)

        return KickstartService.render_template(template_content, variables)

    @staticmethod
    def _build_host_variables(host: Host, repo: RepoStatus) -> dict:
        """根据主机信息构建模板变量"""
        # 计算网关（取IP网段的第一个地址）
        gateway = ""
        if host.ip_address and host.netmask:
            try:
                ip_parts = str(host.ip_address).split(".")
                gateway = f"{ip_parts[0]}.{ip_parts[1]}.{ip_parts[2]}.1"
            except Exception:
                gateway = ""

        # 默认DNS
        nameserver = host.ntp_address or "8.8.8.8"

        # 管理网卡
        nic = host.manage_nic1 or "eth0"

        # Swap 大小（默认8GB）
        swap_size = 8192

        # Root 密码哈希（如果没有则使用默认）
        root_password_hash = "$6$rounds=5000$salt$hashplaceholder"

        return {
            "hostname": host.hostname or "localhost",
            "ip_address": host.ip_address or "",
            "netmask": host.netmask or "255.255.255.0",
            "gateway": gateway,
            "nameserver": nameserver,
            "nic": nic,
            "timezone": "Asia/Shanghai",
            "root_password_hash": root_password_hash,
            "swap_size": swap_size,
            "repo_url": repo.base_url or "",
            "repo_name": repo.name or "",
        }

    @staticmethod
    def _set_none_for_empty(value: Optional[str]) -> str:
        """空值替换为 'none'"""
        return value if value else "none"

    @staticmethod
    def generate_system_conf_file(output_path: str = "/var/www/html/pxe/conf/system.conf") -> dict:
        """生成 system.conf 配置文件

        读取 flag=True 的主机，每行格式：
        serial_number ip_address hostname ntp_address password

        Returns:
            {"success": bool, "message": str, "path": str, "count": int}
        """
        import os
        try:
            hosts = Host.objects.filter(flag=True)
            dir_path = os.path.dirname(output_path)
            if dir_path:
                os.makedirs(dir_path, exist_ok=True)

            lines = []
            for host in hosts:
                line = "{} {} {} {} {}\n".format(
                    KickstartService._set_none_for_empty(host.serial_number),
                    KickstartService._set_none_for_empty(str(host.ip_address) if host.ip_address else ""),
                    KickstartService._set_none_for_empty(host.hostname),
                    KickstartService._set_none_for_empty(host.ntp_address),
                    KickstartService._set_none_for_empty(host.password),
                )
                lines.append(line)

            with open(output_path, "w") as f:
                f.writelines(lines)

            return {
                "success": True,
                "message": "system.conf 生成成功",
                "path": output_path,
                "count": len(lines),
            }
        except Exception as e:
            logger.error(f"Generate system.conf failed: {e}")
            return {"success": False, "message": str(e), "path": output_path, "count": 0}

    @staticmethod
    def generate_network_conf_file(output_path: str = "/var/www/html/pxe/conf/network.conf") -> dict:
        """生成 network.conf 配置文件

        读取 flag=True 的主机，包含管理/存储/业务/其他网络配置

        Returns:
            {"success": bool, "message": str, "path": str, "count": int}
        """
        import os
        try:
            hosts = Host.objects.filter(flag=True)
            dir_path = os.path.dirname(output_path)
            if dir_path:
                os.makedirs(dir_path, exist_ok=True)

            lines = []
            for host in hosts:
                # 管理网络
                if host.manage_nic1:
                    bond_type = host.bond_type or "4"
                    netmask = host.netmask or "255.255.255.0"
                    gateway = ""
                    if host.ip_address:
                        ip_parts = str(host.ip_address).split(".")
                        if len(ip_parts) == 4:
                            ip_parts[3] = "254"
                            gateway = ".".join(ip_parts)
                    line = "{} {} {} {} {} {} {}\n".format(
                        host.serial_number or "none",
                        host.manage_nic1,
                        bond_type,
                        KickstartService._set_none_for_empty(str(host.ip_address) if host.ip_address else ""),
                        netmask,
                        KickstartService._set_none_for_empty(host.manage_vlan),
                        KickstartService._set_none_for_empty(gateway),
                    )
                    lines.append(line)

                # 存储网络
                if host.storage_ifname:
                    storage_netmask = host.storage_netmask or "255.255.255.0"
                    line = "{} {} none {} {} {} none\n".format(
                        host.serial_number or "none",
                        host.storage_ifname,
                        KickstartService._set_none_for_empty(str(host.storage_address) if host.storage_address else ""),
                        storage_netmask,
                        KickstartService._set_none_for_empty(host.storage_vlan),
                    )
                    lines.append(line)

                # 业务网络
                if host.business_ifname:
                    business_bond_type = host.business_bond_type or "4"
                    business_netmask = host.business_netmask or "255.255.255.0"
                    line = "{} {} {} {} {} 1 none\n".format(
                        host.serial_number or "none",
                        host.business_ifname,
                        business_bond_type,
                        KickstartService._set_none_for_empty(str(host.business_address) if host.business_address else ""),
                        business_netmask,
                    )
                    lines.append(line)

                # 其他网络
                if host.other_ifname:
                    other_netmask = host.other_netmask or "255.255.255.0"
                    line = "{} {} none {} {} {} none\n".format(
                        host.serial_number or "none",
                        host.other_ifname,
                        KickstartService._set_none_for_empty(str(host.other_address) if host.other_address else ""),
                        other_netmask,
                        KickstartService._set_none_for_empty(host.other_vlan),
                    )
                    lines.append(line)

            with open(output_path, "w") as f:
                f.writelines(lines)

            return {
                "success": True,
                "message": "network.conf 生成成功",
                "path": output_path,
                "count": len(lines),
            }
        except Exception as e:
            logger.error(f"Generate network.conf failed: {e}")
            return {"success": False, "message": str(e), "path": output_path, "count": 0}

    @staticmethod
    def generate_system_config(hostname: str, timezone: str = "Asia/Shanghai",
                                  root_password_hash: str = None) -> str:
        """生成系统配置段"""
        lines = [
            "# System configuration",
            f"network --hostname={hostname}",
            f"timezone {timezone} --isUtc",
            "auth --enableshadow --passalgo=sha512",
        ]
        if root_password_hash:
            lines.append(f"rootpw --iscrypted {root_password_hash}")
        else:
            lines.append("rootpw --iscrypted $6$rounds=5000$salt$hashplaceholder")
        return "\n".join(lines)

    @staticmethod
    def generate_network_config(interfaces: List[dict]) -> str:
        """生成网络配置段

        Args:
            interfaces: 网卡配置列表，每个元素为 dict:
                {
                    "device": "eth0",
                    "bootproto": "static",
                    "ip": "192.168.1.10",
                    "netmask": "255.255.255.0",
                    "gateway": "192.168.1.1",
                    "nameserver": "8.8.8.8",
                    "onboot": "yes",
                }
        """
        lines = ["# Network configuration"]
        for iface in interfaces:
            device = iface.get("device", "eth0")
            bootproto = iface.get("bootproto", "dhcp")
            if bootproto == "static":
                ip = iface.get("ip", "")
                netmask = iface.get("netmask", "255.255.255.0")
                gateway = iface.get("gateway", "")
                nameserver = iface.get("nameserver", "")
                onboot = iface.get("onboot", "yes")
                cmd = (
                    f"network --bootproto=static --ip={ip} --netmask={netmask} "
                    f"--gateway={gateway} --nameserver={nameserver} --device={device} "
                    f"--onboot={onboot}"
                )
            else:
                onboot = iface.get("onboot", "yes")
                cmd = f"network --bootproto=dhcp --device={device} --onboot={onboot}"
            lines.append(cmd)
        return "\n".join(lines)

    @staticmethod
    def generate_package_config(packages: List[str], groups: List[str] = None) -> str:
        """生成软件包配置段"""
        lines = ["%packages"]
        if groups:
            for group in groups:
                lines.append(f"@{group}")
        for pkg in packages:
            lines.append(pkg)
        lines.append("%end")
        return "\n".join(lines)

    @staticmethod
    def validate_kickstart(content: str) -> dict:
        """验证 Kickstart 模板语法

        返回验证结果：{"valid": bool, "errors": List[str]}
        """
        errors = []

        # 检查必需的指令
        required_sections = ["install", "url"]
        for section in required_sections:
            if section not in content.lower():
                errors.append(f"缺少必需的指令: {section}")

        # 检查是否有未替换的变量
        unmatched = re.findall(r'\{\{([a-zA-Z_][a-zA-Z0-9_]*)\}\}', content)
        if unmatched:
            errors.append(f"存在未替换的变量: {', '.join(set(unmatched))}")

        # 检查分区配置
        if "part" not in content.lower() and "clearpart" not in content.lower():
            errors.append("缺少分区配置 (part/clearpart)")

        # 检查 root 密码
        if "rootpw" not in content.lower():
            errors.append("缺少 root 密码配置 (rootpw)")

        return {
            "valid": len(errors) == 0,
            "errors": errors,
        }

    @staticmethod
    def save_generated_kickstart(name: str, content: str, repo_id: int = None) -> KickStartFileStatus:
        """保存生成的 Kickstart 文件到数据库"""
        defaults = {
            "content": content,
        }
        if repo_id:
            defaults["repo_id"] = repo_id

        kickstart, created = KickStartFileStatus.objects.update_or_create(
            name=name,
            defaults=defaults,
        )
        return kickstart

    @staticmethod
    def seed_default_templates():
        """初始化预置模板到数据库"""
        created_count = 0
        for name, content in KickstartService.TEMPLATES.items():
            _, created = KickStartFileStatus.objects.get_or_create(
                name=name,
                defaults={"content": content, "description": f"预置模板: {name}"},
            )
            if created:
                created_count += 1
        logger.info(f"已初始化 {created_count} 个预置 Kickstart 模板")
        return created_count